config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :posts
  root "posts#index"
  get 'blog', to: 'posts#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,# :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true,
           length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]

  def index
    @posts = Post.order(created_at: :desc).all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def markdown(text)
    options = {
      filer_html:          true,
      hard_wrap:           true,
      space_after_headers: true,
      fenced_code_blocks:  true
    }

    extensions = {
      autolink:           true,
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
  
  def hanja(weekday)
    case weekday
    when 0
      '日'
    when 1
      '月'
    when 2
      '火'
    when 3
      '水'
    when 4
      '木'
    when 5
      '金'
    else
      '土'
    end
  end
end

app/views/layouts/_links.html.erb
<% if admin_signed_in? %>
  <%= link_to "New Post", new_post_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en-US'>
  <head>
  <title>shaybutter.net</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head> 
  <body>

		<div id='navigation'>
			<a href='http://www.shannoncoyne.com'>Projects</a> &nbsp;&nbsp;&nbsp;
			<a href='blog'>Blog</a> &nbsp;&nbsp;&nbsp;
			<a href='https://www.github.com/shannoncoyne'>GitHub</a>
		</div>

		<div id='green'>
			<div id='header'>
				<div id='header-container'>
					<img src='<%= image_path('maccha.png') %>' alt='maccha latte'>
						<div id='offset'>
							<a href='http://www.shaybutter.net'>shaybutter.net</a><br/>
							<span class='hanja latte'>まっちゃラッテ</span>
						</div>
				</div>
			</div>

			<div id='content'>
					<% if notice %><div class='notice'><%= notice %></div><% end %>
					<% if alert %><div class='alert'><%= alert %></div><% end %>
        <%= render 'layouts/links' %>
        <%= yield %>
        <% if admin_signed_in? %>
          <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
        <% end %>
      </div>

			<div id='bottom'>
				<a href='https://www.github.com/shannoncoyne'>
						<img src='<%= image_path('github.png') %>' alt='shannoncoyne @ GitHub'>
				</a>
				<br/>
				<a href='http://www.shaybutter.net'>shaybutter.net</a><br/>
			</div>
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/_post.html.erb
<div class='post'>
	<div class='time'>
		<div class='hanja day'><%= hanja(post.created_at.wday) %></div>
		<span class='month'><%= post.created_at.strftime("%B") %></span><span class='date'><%= post.created_at.strftime("%d") %></span>
	</div>
	<div class='post-left-margin'>
		<div class='subject'>
			<%= link_to post.title, post_path(post) %>
		</div>
		<span class='tag'><a href='#'>#tag</a></span> <span class='tag'><a href='#'>#grapefruit</a></span>
		<div class='post-text'>
			<%= markdown(post.text) %>
      <% if admin_signed_in? %>
        <%= link_to "Edit", edit_post_path(post) %> | 
        <%= link_to "Delete", post, method: :delete,
        data: { confirm: "You sure?" } %>
      <% end %>
    </div>
	</div>
</div>

app/views/posts/edit.html.erb
<%= link_to 'Back to Main Page', posts_path %> | 

<%= link_to 'Back to Post', post_path %>

<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<%= render partial: 'post', locals: {post: post} %>
<% end %>

app/views/posts/new.html.erb
<%= link_to 'Back to Main Page', posts_path %>

<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to 'Back to Main Page', posts_path %>

<%= render partial: 'post', locals: {post: @post} %>